CREATE SEQUENCE SEQ_MAT INCREMENT 5 START 1500;
CREATE TABLE FUNCIONARIO(
	MATRICULA INT PRIMARY KEY DEFAULT NEXTVAL('SEQ_MAT'),
	NOME VARCHAR(100)
)
SELECT * FROM FUNCIONARIO
INSERT INTO FUNCIONARIO(NOME) VALUES('MARIA');
INSERT INTO FUNCIONARIO(NOME) VALUES('PEDRO');
INSERT INTO FUNCIONARIO(NOME) VALUES('JOAO');
INSERT INTO FUNCIONARIO(NOME) VALUES('PAULA');