CREATE TABLE ANIMAIS(
	ID_ANIMAL SERIAL PRIMARY KEY,
	NOME VARCHAR(200),
	ESPECIE VARCHAR(200),
	RACA VARCHAR(200),
	DONO VARCHAR(200)
	)
CREATE TABLE VETERINARIOS(
	ID_VETERINARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(200),
	ESPECIALIDADE VARCHAR(200),
	TELEFONE VARCHAR(20)
)
CREATE TABLE CONSULTAS(
	ID_CONSULTA SERIAL PRIMARY KEY,
	DATA_CONSULTA DATE,
	ID_ANIMAL_FK INT REFERENCES ANIMAIS(ID_ANIMAL),
    ID_VETERINARIO INT REFERENCES VETERINARIOS(ID_VETERINARIO),
    DIAGNOSTICO VARCHAR(200)
)
CREATE TABLE MEDICAMENTOS(
	ID_MEDICAMENTO SERIAL PRIMARY KEY,
	NOME VARCHAR(200),
	DESCRICAO VARCHAR(200),
	DOSAGEM VARCHAR(50)
)
CREATE TABLE CONSULTAS_MEDICAMENTOS (
    ID_CONSULTA INT REFERENCES CONSULTAS(ID_CONSULTA),
    id_medicamento INT REFERENCES MEDICAMENTOS(ID_MEDICAMENTO),
    PRIMARY KEY (ID_CONSULTA, ID_MEDICAMENTO)
);